site_name: sjcab_peak2anno_db
site_description: Gene-backed peak-to-annotation BED resources for SJ/CAB workflows.
site_url: https://sjcab-peak2anno-db.readthedocs.io/
repo_url: https://github.com/stjudecab/sjcab_peak2anno_db
repo_name: stjudecab/sjcab_peak2anno_db

docs_dir: docs
theme:
  name: readthedocs

nav:
  - Home: index.md
