"""Load the package version generated by versioningit during builds."""

try:
    from importlib.metadata import PackageNotFoundError, version
except ImportError:  # pragma: no cover - Python 3.7 compatibility
    try:
        from importlib_metadata import PackageNotFoundError, version
    except ImportError:
        class PackageNotFoundError(Exception):
            """Compatibility exception when package metadata is unavailable."""

        def version(_distribution):
            raise PackageNotFoundError(_distribution)

try:
    from ._generated_version import __version__
except ImportError:
    try:
        __version__ = version("sjcab_peak2anno_db")
    except PackageNotFoundError:
        # Keep imports working directly from a source checkout before installation.
        __version__ = "0.0.0"
