"""Load the package version generated by versioningit during builds."""

from importlib.metadata import PackageNotFoundError, version

try:
    from ._generated_version import __version__
except ImportError:
    try:
        __version__ = version("sjcab_peak2anno_db")
    except PackageNotFoundError:
        # Keep imports working directly from a source checkout before installation.
        __version__ = "0.0.0"
